### ISSUE TITLE
Pkg.add("Blosc.jl") fails due to curl 

### ISSUE THREAD

**Issue by TeroFrondelius** [stevengj/Blosc.jl#29] opened 2016-10-26 17:23 UTC
``` julia
julia> Pkg.add("Blosc")
INFO: Installing BinDeps v0.4.5
INFO: Installing Blosc v0.1.7
INFO: Installing SHA v0.2.1
INFO: Installing URIParser v0.1.6
INFO: Building Blosc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
================================[ ERROR: Blosc ]================================

LoadError: failed process: Process(`curl -f -o c-blosc-1.8.1.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz`, ProcessExited(77)) [77]
while loading /home/tero/.julia/v0.4/Blosc/deps/build.jl, in expression starting on line 18

================================================================================

=================================================================[ BUILD ERRORS ]==================================================================

WARNING: Blosc had build errors.

 - packages with build errors remain installed in /home/tero/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("Blosc")`
 - build a single package by running its `deps/build.jl` script

===================================================================================================================================================
INFO: Package database updated

julia> 
```

workaround: 

``` bash
bash> cd ~/.julia/v0.4/Blosc/deps/
bash> wget https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz
bash> mv v1.8.1.tar.gz c-blosc-1.8.1.tar.gz
bash> 
```

``` julia
julia> Pkg.build("Blosc")
INFO: Building Blosc
```

**Comment by stevengj** [comment] 2016-10-26 17:51
Duplicate of #28?  Though that is only in Julia 0.6.  Still, it seems like the problem is similar: your `curl` certificates are not set up correctly.

**Comment by TeroFrondelius** [comment] 2016-10-26 19:30
Yes it seems so. Sorry for the noise. The #28 title was misleading me, because I was fixed to the idea that  the curl is the problem (because wget works). Anyway I had the same problem both at home and work for both versions 0.4 and 0.5.

**Comment by cmfrtblynmb728** [comment] 2017-01-27 09:19
I am having the same problem. I read #28 , and other threads it referred to. But I didn't get if there is a solution there. Copy paste from another thread I reported the bug: 
 
I am having troubles installing a package called QuantEcon (`Pkg.add("QuantEcon")`). Blosc is part of it. This is the error message I receive. 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
============================================================================[ ERROR: Blosc ]=============================================================================

LoadError: failed process: Process(`curl -f -o c-blosc-1.8.1.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz`, ProcessExited(77)) [77]
while loading /home/alperen/.julia/v0.5/Blosc/deps/build.jl, in expression starting on line 18
```

When I type `Pkg.build("Blosc")`, I get the same result.

Here is the  result of `versioninfo()`:

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

Thanks

**Comment by tkelman** [comment] 2017-01-27 13:12
What linux distribution are you using? If you run `curl -f -o c-blosc-1.8.1.tar.gz -L https://github.com/Blosc/c-blosc/archive/v1.8.1.tar.gz` outside of Julia does it have the same issue?

**Comment by cmfrtblynmb728** [comment] 2017-02-05 07:53
I was using my Ubuntu Machine (16.04.1). 

It turned out to be a certification problem. I don't have the machine with me now but after directing curl to some certificate files (I really don't know much about this issue, sorry) it downloaded files without problem. 

I think I used this method: [http://askubuntu.com/a/733550](http://askubuntu.com/a/733550)

**Comment by stevengj** [comment] 2018-05-17 16:18
Haven't had any reports of this problem for a while, hopefully it is resolved nowadays?

**Closed by stevengj** 2018-05-17 16:18 UTC

**Comment by Goysa2** [comment] 2018-05-29 19:41
I have a very similar problem on a different package, is there a solution?
